name: Test

on:
  push:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests with pytest
        env:
          SECRET_KEY: ${{secrets.APP_SECRET_KEY}}
          DATABASE_URL: ${{secrets.APP_DATABASE_URL}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          GITHUB_CLIENT_ID: ${{secrets.GHUB_CLIENT_ID}}
          GITHUB_CLIENT_SECRET: ${{secrets.GHUB_CLIENT_SECRET}}
        run: pytest
